//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalsBreedingAdvicer.Properties.PalsData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PalNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PalNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PalsBreedingAdvicer.Properties.PalsData.PalNames", typeof(PalNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melpaca.
        /// </summary>
        public static string Alpaca {
            get {
                return ResourceManager.GetString("Alpaca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitsun.
        /// </summary>
        public static string AmaterasuWolf {
            get {
                return ResourceManager.GetString("AmaterasuWolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitsun Noct.
        /// </summary>
        public static string AmaterasuWolf_Dark {
            get {
                return ResourceManager.GetString("AmaterasuWolf_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anubis.
        /// </summary>
        public static string Anubis {
            get {
                return ResourceManager.GetString("Anubis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyafia.
        /// </summary>
        public static string BadCatgirl {
            get {
                return ResourceManager.GetString("BadCatgirl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incineram.
        /// </summary>
        public static string Baphomet {
            get {
                return ResourceManager.GetString("Baphomet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incineram Noct.
        /// </summary>
        public static string Baphomet_Dark {
            get {
                return ResourceManager.GetString("Baphomet_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau.
        /// </summary>
        public static string Bastet {
            get {
                return ResourceManager.GetString("Bastet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau Cryst.
        /// </summary>
        public static string Bastet_Ice {
            get {
                return ResourceManager.GetString("Bastet_Ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caprity.
        /// </summary>
        public static string BerryGoat {
            get {
                return ResourceManager.GetString("BerryGoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caprity Noct.
        /// </summary>
        public static string BerryGoat_Dark {
            get {
                return ResourceManager.GetString("BerryGoat_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanwyrm.
        /// </summary>
        public static string BirdDragon {
            get {
                return ResourceManager.GetString("BirdDragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanwyrm Cryst.
        /// </summary>
        public static string BirdDragon_Ice {
            get {
                return ResourceManager.GetString("BirdDragon_Ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necromus.
        /// </summary>
        public static string BlackCentaur {
            get {
                return ResourceManager.GetString("BlackCentaur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadowbeak.
        /// </summary>
        public static string BlackGriffon {
            get {
                return ResourceManager.GetString("BlackGriffon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astegon.
        /// </summary>
        public static string BlackMetalDragon {
            get {
                return ResourceManager.GetString("BlackMetalDragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smokie.
        /// </summary>
        public static string BlackPuppy {
            get {
                return ResourceManager.GetString("BlackPuppy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prunelia.
        /// </summary>
        public static string BlueberryFairy {
            get {
                return ResourceManager.GetString("BlueberryFairy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azurobe.
        /// </summary>
        public static string BlueDragon {
            get {
                return ResourceManager.GetString("BlueDragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuack.
        /// </summary>
        public static string BluePlatypus {
            get {
                return ResourceManager.GetString("BluePlatypus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azurmane.
        /// </summary>
        public static string BlueThunderHorse {
            get {
                return ResourceManager.GetString("BlueThunderHorse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rushoar.
        /// </summary>
        public static string Boar {
            get {
                return ResourceManager.GetString("Boar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sootseer.
        /// </summary>
        public static string CandleGhost {
            get {
                return ResourceManager.GetString("CandleGhost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penking.
        /// </summary>
        public static string CaptainPenguin {
            get {
                return ResourceManager.GetString("CaptainPenguin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifmunk.
        /// </summary>
        public static string Carbunclo {
            get {
                return ResourceManager.GetString("Carbunclo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tombat.
        /// </summary>
        public static string CatBat {
            get {
                return ResourceManager.GetString("CatBat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katress.
        /// </summary>
        public static string CatMage {
            get {
                return ResourceManager.GetString("CatMage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katress Ignis.
        /// </summary>
        public static string CatMage_Fire {
            get {
                return ResourceManager.GetString("CatMage_Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felbat.
        /// </summary>
        public static string CatVampire {
            get {
                return ResourceManager.GetString("CatVampire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chikipi.
        /// </summary>
        public static string ChickenPal {
            get {
                return ResourceManager.GetString("ChickenPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tocotoco.
        /// </summary>
        public static string ColorfulBird {
            get {
                return ResourceManager.GetString("ColorfulBird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozzarina.
        /// </summary>
        public static string CowPal {
            get {
                return ResourceManager.GetString("CowPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinnamoth.
        /// </summary>
        public static string CuteButterfly {
            get {
                return ResourceManager.GetString("CuteButterfly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vixy.
        /// </summary>
        public static string CuteFox {
            get {
                return ResourceManager.GetString("CuteFox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuddler.
        /// </summary>
        public static string CuteMole {
            get {
                return ResourceManager.GetString("CuteMole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xenovader.
        /// </summary>
        public static string DarkAlien {
            get {
                return ResourceManager.GetString("DarkAlien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cawgnito.
        /// </summary>
        public static string DarkCrow {
            get {
                return ResourceManager.GetString("DarkCrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xenolord.
        /// </summary>
        public static string DarkMechaDragon {
            get {
                return ResourceManager.GetString("DarkMechaDragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menasting.
        /// </summary>
        public static string DarkScorpion {
            get {
                return ResourceManager.GetString("DarkScorpion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menasting Terra.
        /// </summary>
        public static string DarkScorpion_Ground {
            get {
                return ResourceManager.GetString("DarkScorpion_Ground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eikthyrdeer.
        /// </summary>
        public static string Deer {
            get {
                return ResourceManager.GetString("Deer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eikthyrdeer Terra.
        /// </summary>
        public static string Deer_Ground {
            get {
                return ResourceManager.GetString("Deer_Ground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daedream.
        /// </summary>
        public static string DreamDemon {
            get {
                return ResourceManager.GetString("DreamDemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digtoise.
        /// </summary>
        public static string DrillGame {
            get {
                return ResourceManager.GetString("DrillGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galeclaw.
        /// </summary>
        public static string Eagle {
            get {
                return ResourceManager.GetString("Eagle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparkit.
        /// </summary>
        public static string ElecCat {
            get {
                return ResourceManager.GetString("ElecCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grizzbolt.
        /// </summary>
        public static string ElecPanda {
            get {
                return ResourceManager.GetString("ElecPanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elphidran.
        /// </summary>
        public static string FairyDragon {
            get {
                return ResourceManager.GetString("FairyDragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elphidran Aqua.
        /// </summary>
        public static string FairyDragon_Water {
            get {
                return ResourceManager.GetString("FairyDragon_Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dazemu.
        /// </summary>
        public static string FeatherOstrich {
            get {
                return ResourceManager.GetString("FeatherOstrich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fenglope.
        /// </summary>
        public static string FengyunDeeper {
            get {
                return ResourceManager.GetString("FengyunDeeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fenglope Lux.
        /// </summary>
        public static string FengyunDeeper_Electric {
            get {
                return ResourceManager.GetString("FengyunDeeper_Electric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pyrin.
        /// </summary>
        public static string FireKirin {
            get {
                return ResourceManager.GetString("FireKirin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pyrin Noct.
        /// </summary>
        public static string FireKirin_Dark {
            get {
                return ResourceManager.GetString("FireKirin_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooby.
        /// </summary>
        public static string FlameBambi {
            get {
                return ResourceManager.GetString("FlameBambi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arsox.
        /// </summary>
        public static string FlameBuffalo {
            get {
                return ResourceManager.GetString("FlameBuffalo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinossom.
        /// </summary>
        public static string FlowerDinosaur {
            get {
                return ResourceManager.GetString("FlowerDinosaur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinossom Lux.
        /// </summary>
        public static string FlowerDinosaur_Electric {
            get {
                return ResourceManager.GetString("FlowerDinosaur_Electric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petallia.
        /// </summary>
        public static string FlowerDoll {
            get {
                return ResourceManager.GetString("FlowerDoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flopie.
        /// </summary>
        public static string FlowerRabbit {
            get {
                return ResourceManager.GetString("FlowerRabbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celaray.
        /// </summary>
        public static string FlyingManta {
            get {
                return ResourceManager.GetString("FlyingManta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wixen.
        /// </summary>
        public static string FoxMage {
            get {
                return ResourceManager.GetString("FoxMage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wixen Noct.
        /// </summary>
        public static string FoxMage_Dark {
            get {
                return ResourceManager.GetString("FoxMage_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teafant.
        /// </summary>
        public static string Ganesha {
            get {
                return ResourceManager.GetString("Ganesha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direhowl.
        /// </summary>
        public static string Garm {
            get {
                return ResourceManager.GetString("Garm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maraith.
        /// </summary>
        public static string GhostBeast {
            get {
                return ResourceManager.GetString("GhostBeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitemary.
        /// </summary>
        public static string GhostRabbit {
            get {
                return ResourceManager.GetString("GhostRabbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gildane.
        /// </summary>
        public static string GoldenHorse {
            get {
                return ResourceManager.GetString("GoldenHorse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gorirat.
        /// </summary>
        public static string Gorilla {
            get {
                return ResourceManager.GetString("Gorilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gorirat Terra.
        /// </summary>
        public static string Gorilla_Ground {
            get {
                return ResourceManager.GetString("Gorilla_Ground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mammorest.
        /// </summary>
        public static string GrassMammoth {
            get {
                return ResourceManager.GetString("GrassMammoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mammorest Cryst.
        /// </summary>
        public static string GrassMammoth_Ice {
            get {
                return ResourceManager.GetString("GrassMammoth_Ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mossanda.
        /// </summary>
        public static string GrassPanda {
            get {
                return ResourceManager.GetString("GrassPanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mossanda Lux.
        /// </summary>
        public static string GrassPanda_Electric {
            get {
                return ResourceManager.GetString("GrassPanda_Electric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdash.
        /// </summary>
        public static string GrassRabbitMan {
            get {
                return ResourceManager.GetString("GrassRabbitMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splatterina.
        /// </summary>
        public static string GrimGirl {
            get {
                return ResourceManager.GetString("GrimGirl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yakumo.
        /// </summary>
        public static string GuardianDog {
            get {
                return ResourceManager.GetString("GuardianDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helzephyr.
        /// </summary>
        public static string HadesBird {
            get {
                return ResourceManager.GetString("HadesBird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helzephyr Lux.
        /// </summary>
        public static string HadesBird_Electric {
            get {
                return ResourceManager.GetString("HadesBird_Electric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitewing.
        /// </summary>
        public static string HawkBird {
            get {
                return ResourceManager.GetString("HawkBird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jolthog.
        /// </summary>
        public static string Hedgehog {
            get {
                return ResourceManager.GetString("Hedgehog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jolthog Cryst.
        /// </summary>
        public static string Hedgehog_Ice {
            get {
                return ResourceManager.GetString("Hedgehog_Ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warsect.
        /// </summary>
        public static string HerculesBeetle {
            get {
                return ResourceManager.GetString("HerculesBeetle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warsect Terra.
        /// </summary>
        public static string HerculesBeetle_Ground {
            get {
                return ResourceManager.GetString("HerculesBeetle_Ground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faleris.
        /// </summary>
        public static string Horus {
            get {
                return ResourceManager.GetString("Horus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faleris Aqua.
        /// </summary>
        public static string Horus_Water {
            get {
                return ResourceManager.GetString("Horus_Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reindrix.
        /// </summary>
        public static string IceDeer {
            get {
                return ResourceManager.GetString("IceDeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foxcicle.
        /// </summary>
        public static string IceFox {
            get {
                return ResourceManager.GetString("IceFox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frostallion.
        /// </summary>
        public static string IceHorse {
            get {
                return ResourceManager.GetString("IceHorse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frostallion Noct.
        /// </summary>
        public static string IceHorse_Dark {
            get {
                return ResourceManager.GetString("IceHorse_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jetragon.
        /// </summary>
        public static string JetDragon {
            get {
                return ResourceManager.GetString("JetDragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelpsea.
        /// </summary>
        public static string Kelpie {
            get {
                return ResourceManager.GetString("Kelpie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelpsea Ignis.
        /// </summary>
        public static string Kelpie_Fire {
            get {
                return ResourceManager.GetString("Kelpie_Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croajiro.
        /// </summary>
        public static string KendoFrog {
            get {
                return ResourceManager.GetString("KendoFrog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kingpaca.
        /// </summary>
        public static string KingAlpaca {
            get {
                return ResourceManager.GetString("KingAlpaca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kingpaca Cryst.
        /// </summary>
        public static string KingAlpaca_Ice {
            get {
                return ResourceManager.GetString("KingAlpaca_Ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blazamut.
        /// </summary>
        public static string KingBahamut {
            get {
                return ResourceManager.GetString("KingBahamut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blazamut Ryu.
        /// </summary>
        public static string KingBahamut_Dragon {
            get {
                return ResourceManager.GetString("KingBahamut_Dragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Univolt.
        /// </summary>
        public static string Kirin {
            get {
                return ResourceManager.GetString("Kirin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foxparks.
        /// </summary>
        public static string Kitsunebi {
            get {
                return ResourceManager.GetString("Kitsunebi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foxparks Cryst.
        /// </summary>
        public static string Kitsunebi_Ice {
            get {
                return ResourceManager.GetString("Kitsunebi_Ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flambelle.
        /// </summary>
        public static string LavaGirl {
            get {
                return ResourceManager.GetString("LavaGirl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dumud.
        /// </summary>
        public static string LazyCatfish {
            get {
                return ResourceManager.GetString("LazyCatfish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaxaurus.
        /// </summary>
        public static string LazyDragon {
            get {
                return ResourceManager.GetString("LazyDragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaxaurus Lux.
        /// </summary>
        public static string LazyDragon_Electric {
            get {
                return ResourceManager.GetString("LazyDragon_Electric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lullu.
        /// </summary>
        public static string LeafPrincess {
            get {
                return ResourceManager.GetString("LeafPrincess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyleen.
        /// </summary>
        public static string LilyQueen {
            get {
                return ResourceManager.GetString("LilyQueen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyleen Noct.
        /// </summary>
        public static string LilyQueen_Dark {
            get {
                return ResourceManager.GetString("LilyQueen_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bristla.
        /// </summary>
        public static string LittleBriarRose {
            get {
                return ResourceManager.GetString("LittleBriarRose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leezpunk.
        /// </summary>
        public static string LizardMan {
            get {
                return ResourceManager.GetString("LizardMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leezpunk Ignis.
        /// </summary>
        public static string LizardMan_Fire {
            get {
                return ResourceManager.GetString("LizardMan_Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blazehowl.
        /// </summary>
        public static string Manticore {
            get {
                return ResourceManager.GetString("Manticore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blazehowl Noct.
        /// </summary>
        public static string Manticore_Dark {
            get {
                return ResourceManager.GetString("Manticore_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mimog.
        /// </summary>
        public static string MimicDog {
            get {
                return ResourceManager.GetString("MimicDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanzee.
        /// </summary>
        public static string Monkey {
            get {
                return ResourceManager.GetString("Monkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selyne.
        /// </summary>
        public static string MoonQueen {
            get {
                return ResourceManager.GetString("MoonQueen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swee.
        /// </summary>
        public static string MopBaby {
            get {
                return ResourceManager.GetString("MopBaby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweepa.
        /// </summary>
        public static string MopKing {
            get {
                return ResourceManager.GetString("MopKing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shroomer.
        /// </summary>
        public static string MushroomDragon {
            get {
                return ResourceManager.GetString("MushroomDragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shroomer Noct.
        /// </summary>
        public static string MushroomDragon_Dark {
            get {
                return ResourceManager.GetString("MushroomDragon_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunaris.
        /// </summary>
        public static string Mutant {
            get {
                return ResourceManager.GetString("Mutant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omascul.
        /// </summary>
        public static string MysteryMask {
            get {
                return ResourceManager.GetString("MysteryMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grintale.
        /// </summary>
        public static string NaughtyCat {
            get {
                return ResourceManager.GetString("NaughtyCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depresso.
        /// </summary>
        public static string NegativeKoala {
            get {
                return ResourceManager.GetString("NegativeKoala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killamari.
        /// </summary>
        public static string NegativeOctopus {
            get {
                return ResourceManager.GetString("NegativeOctopus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starryon.
        /// </summary>
        public static string NightBlueHorse {
            get {
                return ResourceManager.GetString("NightBlueHorse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nox.
        /// </summary>
        public static string NightFox {
            get {
                return ResourceManager.GetString("NightFox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bellanoir.
        /// </summary>
        public static string NightLady {
            get {
                return ResourceManager.GetString("NightLady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bellanoir Libero.
        /// </summary>
        public static string NightLady_Dark {
            get {
                return ResourceManager.GetString("NightLady_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pengullet.
        /// </summary>
        public static string Penguin {
            get {
                return ResourceManager.GetString("Penguin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cattiva.
        /// </summary>
        public static string PinkCat {
            get {
                return ResourceManager.GetString("PinkCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lovander.
        /// </summary>
        public static string PinkLizard {
            get {
                return ResourceManager.GetString("PinkLizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ribbuny.
        /// </summary>
        public static string PinkRabbit {
            get {
                return ResourceManager.GetString("PinkRabbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ribbuny Botan.
        /// </summary>
        public static string PinkRabbit_Grass {
            get {
                return ResourceManager.GetString("PinkRabbit_Grass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gumoss.
        /// </summary>
        public static string PlantSlime {
            get {
                return ResourceManager.GetString("PlantSlime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gumoss (Flower).
        /// </summary>
        public static string PlantSlime_Flower {
            get {
                return ResourceManager.GetString("PlantSlime_Flower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarantriss.
        /// </summary>
        public static string PurpleSpider {
            get {
                return ResourceManager.GetString("PurpleSpider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elizabee.
        /// </summary>
        public static string QueenBee {
            get {
                return ResourceManager.GetString("QueenBee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dazzi.
        /// </summary>
        public static string RaijinDaughter {
            get {
                return ResourceManager.GetString("RaijinDaughter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dazzi Noct.
        /// </summary>
        public static string RaijinDaughter_Water {
            get {
                return ResourceManager.GetString("RaijinDaughter_Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ragnahawk.
        /// </summary>
        public static string RedArmorBird {
            get {
                return ResourceManager.GetString("RedArmorBird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robinquill.
        /// </summary>
        public static string RobinHood {
            get {
                return ResourceManager.GetString("RobinHood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robinquill Terra.
        /// </summary>
        public static string RobinHood_Ground {
            get {
                return ResourceManager.GetString("RobinHood_Ground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bushi.
        /// </summary>
        public static string Ronin {
            get {
                return ResourceManager.GetString("Ronin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bushi Noct.
        /// </summary>
        public static string Ronin_Dark {
            get {
                return ResourceManager.GetString("Ronin_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paladius.
        /// </summary>
        public static string SaintCentaur {
            get {
                return ResourceManager.GetString("SaintCentaur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broncherry.
        /// </summary>
        public static string SakuraSaurus {
            get {
                return ResourceManager.GetString("SakuraSaurus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broncherry Aqua.
        /// </summary>
        public static string SakuraSaurus_Water {
            get {
                return ResourceManager.GetString("SakuraSaurus_Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prixter.
        /// </summary>
        public static string ScorpionMan {
            get {
                return ResourceManager.GetString("ScorpionMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surfent.
        /// </summary>
        public static string Serpent {
            get {
                return ResourceManager.GetString("Serpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surfent Terra.
        /// </summary>
        public static string Serpent_Ground {
            get {
                return ResourceManager.GetString("Serpent_Ground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gobfin.
        /// </summary>
        public static string SharkKid {
            get {
                return ResourceManager.GetString("SharkKid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gobfin Ignis.
        /// </summary>
        public static string SharkKid_Fire {
            get {
                return ResourceManager.GetString("SharkKid_Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamball.
        /// </summary>
        public static string SheepBall {
            get {
                return ResourceManager.GetString("SheepBall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dogen.
        /// </summary>
        public static string SifuDog {
            get {
                return ResourceManager.GetString("SifuDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quivern.
        /// </summary>
        public static string SkyDragon {
            get {
                return ResourceManager.GetString("SkyDragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quivern Botan.
        /// </summary>
        public static string SkyDragon_Grass {
            get {
                return ResourceManager.GetString("SkyDragon_Grass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kikit.
        /// </summary>
        public static string SmallArmadillo {
            get {
                return ResourceManager.GetString("SmallArmadillo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bastigor.
        /// </summary>
        public static string SnowTigerBeastman {
            get {
                return ResourceManager.GetString("SnowTigerBeastman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beegarde.
        /// </summary>
        public static string SoldierBee {
            get {
                return ResourceManager.GetString("SoldierBee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suzaku.
        /// </summary>
        public static string Suzaku {
            get {
                return ResourceManager.GetString("Suzaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suzaku Aqua.
        /// </summary>
        public static string Suzaku_Water {
            get {
                return ResourceManager.GetString("Suzaku_Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woolipop.
        /// </summary>
        public static string SweetsSheep {
            get {
                return ResourceManager.GetString("SweetsSheep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beakon.
        /// </summary>
        public static string ThunderBird {
            get {
                return ResourceManager.GetString("ThunderBird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rayhound.
        /// </summary>
        public static string ThunderDog {
            get {
                return ResourceManager.GetString("ThunderDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orserk.
        /// </summary>
        public static string ThunderDragonMan {
            get {
                return ResourceManager.GetString("ThunderDragonMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jormuntide.
        /// </summary>
        public static string Umihebi {
            get {
                return ResourceManager.GetString("Umihebi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jormuntide Ignis.
        /// </summary>
        public static string Umihebi_Fire {
            get {
                return ResourceManager.GetString("Umihebi_Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaelet.
        /// </summary>
        public static string VioletFairy {
            get {
                return ResourceManager.GetString("VioletFairy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reptyro.
        /// </summary>
        public static string VolcanicMonster {
            get {
                return ResourceManager.GetString("VolcanicMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reptyro Cryst.
        /// </summary>
        public static string VolcanicMonster_Ice {
            get {
                return ResourceManager.GetString("VolcanicMonster_Ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chillet.
        /// </summary>
        public static string WeaselDragon {
            get {
                return ResourceManager.GetString("WeaselDragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chillet Ignis.
        /// </summary>
        public static string WeaselDragon_Fire {
            get {
                return ResourceManager.GetString("WeaselDragon_Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loupmoon.
        /// </summary>
        public static string Werewolf {
            get {
                return ResourceManager.GetString("Werewolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loupmoon Cryst.
        /// </summary>
        public static string Werewolf_Ice {
            get {
                return ResourceManager.GetString("Werewolf_Ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xenogard.
        /// </summary>
        public static string WhiteAlienDragon {
            get {
                return ResourceManager.GetString("WhiteAlienDragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celesdir.
        /// </summary>
        public static string WhiteDeer {
            get {
                return ResourceManager.GetString("WhiteDeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sibelyx.
        /// </summary>
        public static string WhiteMoth {
            get {
                return ResourceManager.GetString("WhiteMoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silvegis.
        /// </summary>
        public static string WhiteShieldDragon {
            get {
                return ResourceManager.GetString("WhiteShieldDragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryolinx.
        /// </summary>
        public static string WhiteTiger {
            get {
                return ResourceManager.GetString("WhiteTiger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryolinx Terra.
        /// </summary>
        public static string WhiteTiger_Ground {
            get {
                return ResourceManager.GetString("WhiteTiger_Ground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hangyu.
        /// </summary>
        public static string WindChimes {
            get {
                return ResourceManager.GetString("WindChimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hangyu Cryst.
        /// </summary>
        public static string WindChimes_Ice {
            get {
                return ResourceManager.GetString("WindChimes_Ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knocklem.
        /// </summary>
        public static string WingGolem {
            get {
                return ResourceManager.GetString("WingGolem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoocrates.
        /// </summary>
        public static string WizardOwl {
            get {
                return ResourceManager.GetString("WizardOwl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cremis.
        /// </summary>
        public static string WoolFox {
            get {
                return ResourceManager.GetString("WoolFox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wumpo.
        /// </summary>
        public static string Yeti {
            get {
                return ResourceManager.GetString("Yeti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wumpo Botan.
        /// </summary>
        public static string Yeti_Grass {
            get {
                return ResourceManager.GetString("Yeti_Grass", resourceCulture);
            }
        }
    }
}
