//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalsBreedingAdvicer.Properties.PalsData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PalPassiveSkillNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PalPassiveSkillNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PalsBreedingAdvicer.Properties.PalsData.PalPassiveSkillNames", typeof(PalPassiveSkillNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otherworldly Cells.
        /// </summary>
        public static string Alien {
            get {
                return ResourceManager.GetString("Alien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easygoing.
        /// </summary>
        public static string CoolTimeReduction_Down_1 {
            get {
                return ResourceManager.GetString("CoolTimeReduction_Down_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serenity.
        /// </summary>
        public static string CoolTimeReduction_Up_1 {
            get {
                return ResourceManager.GetString("CoolTimeReduction_Up_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impatient.
        /// </summary>
        public static string CoolTimeReduction_Up_2 {
            get {
                return ResourceManager.GetString("CoolTimeReduction_Up_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clumsy.
        /// </summary>
        public static string CraftSpeed_down1 {
            get {
                return ResourceManager.GetString("CraftSpeed_down1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slacker.
        /// </summary>
        public static string CraftSpeed_down2 {
            get {
                return ResourceManager.GetString("CraftSpeed_down2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serious.
        /// </summary>
        public static string CraftSpeed_up1 {
            get {
                return ResourceManager.GetString("CraftSpeed_up1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artisan.
        /// </summary>
        public static string CraftSpeed_up2 {
            get {
                return ResourceManager.GetString("CraftSpeed_up2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarkable Craftsmanship.
        /// </summary>
        public static string CraftSpeed_up3 {
            get {
                return ResourceManager.GetString("CraftSpeed_up3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downtrodden.
        /// </summary>
        public static string Deffence_down1 {
            get {
                return ResourceManager.GetString("Deffence_down1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brittle.
        /// </summary>
        public static string Deffence_down2 {
            get {
                return ResourceManager.GetString("Deffence_down2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Skin.
        /// </summary>
        public static string Deffence_up1 {
            get {
                return ResourceManager.GetString("Deffence_up1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burly Body.
        /// </summary>
        public static string Deffence_up2 {
            get {
                return ResourceManager.GetString("Deffence_up2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamond Body.
        /// </summary>
        public static string Deffence_up3 {
            get {
                return ResourceManager.GetString("Deffence_up3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydromaniac.
        /// </summary>
        public static string ElementBoost_Aqua_1_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Aqua_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lord of the Sea.
        /// </summary>
        public static string ElementBoost_Aqua_2_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Aqua_2_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veil of Darkness.
        /// </summary>
        public static string ElementBoost_Dark_1_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Dark_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lord of the Underworld.
        /// </summary>
        public static string ElementBoost_Dark_2_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Dark_2_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood of the Dragon.
        /// </summary>
        public static string ElementBoost_Dragon_1_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Dragon_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divine Dragon.
        /// </summary>
        public static string ElementBoost_Dragon_2_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Dragon_2_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power of Gaia.
        /// </summary>
        public static string ElementBoost_Earth_1_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Earth_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth Emperor.
        /// </summary>
        public static string ElementBoost_Earth_2_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Earth_2_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pyromaniac.
        /// </summary>
        public static string ElementBoost_Fire_1_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Fire_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flame Emperor.
        /// </summary>
        public static string ElementBoost_Fire_2_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Fire_2_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coldblooded.
        /// </summary>
        public static string ElementBoost_Ice_1_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Ice_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Emperor.
        /// </summary>
        public static string ElementBoost_Ice_2_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Ice_2_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragrant Foliage.
        /// </summary>
        public static string ElementBoost_Leaf_1_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Leaf_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spirit Emperor.
        /// </summary>
        public static string ElementBoost_Leaf_2_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Leaf_2_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zen Mind.
        /// </summary>
        public static string ElementBoost_Normal_1_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Normal_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celestial Emperor.
        /// </summary>
        public static string ElementBoost_Normal_2_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Normal_2_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacitor.
        /// </summary>
        public static string ElementBoost_Thunder_1_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Thunder_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lord of Lightning.
        /// </summary>
        public static string ElementBoost_Thunder_2_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Thunder_2_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waterproof.
        /// </summary>
        public static string ElementResist_Aqua_1_PAL {
            get {
                return ResourceManager.GetString("ElementResist_Aqua_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheery.
        /// </summary>
        public static string ElementResist_Dark_1_PAL {
            get {
                return ResourceManager.GetString("ElementResist_Dark_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragonkiller.
        /// </summary>
        public static string ElementResist_Dragon_1_PAL {
            get {
                return ResourceManager.GetString("ElementResist_Dragon_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earthquake Resistant.
        /// </summary>
        public static string ElementResist_Earth_1_PAL {
            get {
                return ResourceManager.GetString("ElementResist_Earth_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suntan Lover.
        /// </summary>
        public static string ElementResist_Fire_1_PAL {
            get {
                return ResourceManager.GetString("ElementResist_Fire_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heated Body.
        /// </summary>
        public static string ElementResist_Ice_1_PAL {
            get {
                return ResourceManager.GetString("ElementResist_Ice_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Botanical Barrier.
        /// </summary>
        public static string ElementResist_Leaf_1_PAL {
            get {
                return ResourceManager.GetString("ElementResist_Leaf_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abnormal.
        /// </summary>
        public static string ElementResist_Normal_1_PAL {
            get {
                return ResourceManager.GetString("ElementResist_Normal_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insulated Body.
        /// </summary>
        public static string ElementResist_Thunder_1_PAL {
            get {
                return ResourceManager.GetString("ElementResist_Thunder_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eternal Flame.
        /// </summary>
        public static string EternalFlame {
            get {
                return ResourceManager.GetString("EternalFlame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invader.
        /// </summary>
        public static string Invader {
            get {
                return ResourceManager.GetString("Invader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimble.
        /// </summary>
        public static string MoveSpeed_up_1 {
            get {
                return ResourceManager.GetString("MoveSpeed_up_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runner.
        /// </summary>
        public static string MoveSpeed_up_2 {
            get {
                return ResourceManager.GetString("MoveSpeed_up_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swift.
        /// </summary>
        public static string MoveSpeed_up_3 {
            get {
                return ResourceManager.GetString("MoveSpeed_up_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nocturnal.
        /// </summary>
        public static string Nocturnal {
            get {
                return ResourceManager.GetString("Nocturnal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercy Hit.
        /// </summary>
        public static string NonKilling {
            get {
                return ResourceManager.GetString("NonKilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musclehead.
        /// </summary>
        public static string Noukin {
            get {
                return ResourceManager.GetString("Noukin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coward.
        /// </summary>
        public static string PAL_ALLAttack_down1 {
            get {
                return ResourceManager.GetString("PAL_ALLAttack_down1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacifist.
        /// </summary>
        public static string PAL_ALLAttack_down2 {
            get {
                return ResourceManager.GetString("PAL_ALLAttack_down2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brave.
        /// </summary>
        public static string PAL_ALLAttack_up1 {
            get {
                return ResourceManager.GetString("PAL_ALLAttack_up1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferocious.
        /// </summary>
        public static string PAL_ALLAttack_up2 {
            get {
                return ResourceManager.GetString("PAL_ALLAttack_up2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demon God.
        /// </summary>
        public static string PAL_ALLAttack_up3 {
            get {
                return ResourceManager.GetString("PAL_ALLAttack_up3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conceited.
        /// </summary>
        public static string PAL_conceited {
            get {
                return ResourceManager.GetString("PAL_conceited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Slave.
        /// </summary>
        public static string PAL_CorporateSlave {
            get {
                return ResourceManager.GetString("PAL_CorporateSlave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dainty Eater.
        /// </summary>
        public static string PAL_FullStomach_Down_1 {
            get {
                return ResourceManager.GetString("PAL_FullStomach_Down_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet Lover.
        /// </summary>
        public static string PAL_FullStomach_Down_2 {
            get {
                return ResourceManager.GetString("PAL_FullStomach_Down_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mastery of Fasting.
        /// </summary>
        public static string PAL_FullStomach_Down_3 {
            get {
                return ResourceManager.GetString("PAL_FullStomach_Down_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glutton.
        /// </summary>
        public static string PAL_FullStomach_Up_1 {
            get {
                return ResourceManager.GetString("PAL_FullStomach_Up_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottomless Stomach.
        /// </summary>
        public static string PAL_FullStomach_Up_2 {
            get {
                return ResourceManager.GetString("PAL_FullStomach_Up_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masochist.
        /// </summary>
        public static string PAL_masochist {
            get {
                return ResourceManager.GetString("PAL_masochist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggressive.
        /// </summary>
        public static string PAL_oraora {
            get {
                return ResourceManager.GetString("PAL_oraora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hooligan.
        /// </summary>
        public static string PAL_rude {
            get {
                return ResourceManager.GetString("PAL_rude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadist.
        /// </summary>
        public static string PAL_sadist {
            get {
                return ResourceManager.GetString("PAL_sadist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive Thinker.
        /// </summary>
        public static string PAL_Sanity_Down_1 {
            get {
                return ResourceManager.GetString("PAL_Sanity_Down_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workaholic.
        /// </summary>
        public static string PAL_Sanity_Down_2 {
            get {
                return ResourceManager.GetString("PAL_Sanity_Down_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart of the Immovable King.
        /// </summary>
        public static string PAL_Sanity_Down_3 {
            get {
                return ResourceManager.GetString("PAL_Sanity_Down_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unstable.
        /// </summary>
        public static string PAL_Sanity_Up_1 {
            get {
                return ResourceManager.GetString("PAL_Sanity_Up_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destructive.
        /// </summary>
        public static string PAL_Sanity_Up_2 {
            get {
                return ResourceManager.GetString("PAL_Sanity_Up_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucky.
        /// </summary>
        public static string Rare {
            get {
                return ResourceManager.GetString("Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shabby.
        /// </summary>
        public static string SalePrice_Down_1 {
            get {
                return ResourceManager.GetString("SalePrice_Down_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noble.
        /// </summary>
        public static string SalePrice_Up_1 {
            get {
                return ResourceManager.GetString("SalePrice_Up_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine Furs.
        /// </summary>
        public static string SalePrice_Up_2 {
            get {
                return ResourceManager.GetString("SalePrice_Up_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sickly.
        /// </summary>
        public static string Stamina_Down_1 {
            get {
                return ResourceManager.GetString("Stamina_Down_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinite Stamina.
        /// </summary>
        public static string Stamina_Up_1 {
            get {
                return ResourceManager.GetString("Stamina_Up_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit as a Fiddle.
        /// </summary>
        public static string Stamina_Up_2 {
            get {
                return ResourceManager.GetString("Stamina_Up_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eternal Engine.
        /// </summary>
        public static string Stamina_Up_3 {
            get {
                return ResourceManager.GetString("Stamina_Up_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Philantrophist.
        /// </summary>
        public static string Test_PalEgg_HatchingSpeed_Up {
            get {
                return ResourceManager.GetString("Test_PalEgg_HatchingSpeed_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanguard.
        /// </summary>
        public static string TrainerATK_UP_1 {
            get {
                return ResourceManager.GetString("TrainerATK_UP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stronghold Strategist.
        /// </summary>
        public static string TrainerDEF_UP_1 {
            get {
                return ResourceManager.GetString("TrainerDEF_UP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging Foreman.
        /// </summary>
        public static string TrainerLogging_up1 {
            get {
                return ResourceManager.GetString("TrainerLogging_up1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mine Foreman.
        /// </summary>
        public static string TrainerMining_up1 {
            get {
                return ResourceManager.GetString("TrainerMining_up1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivational Leader.
        /// </summary>
        public static string TrainerWorkSpeed_UP_1 {
            get {
                return ResourceManager.GetString("TrainerWorkSpeed_UP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vampiric.
        /// </summary>
        public static string Vampire {
            get {
                return ResourceManager.GetString("Vampire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siren of the Void.
        /// </summary>
        public static string Witch {
            get {
                return ResourceManager.GetString("Witch", resourceCulture);
            }
        }
    }
}
