//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalsBreedingAdvicer.Properties.PalsData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PalPassiveSkillDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PalPassiveSkillDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PalsBreedingAdvicer.Properties.PalsData.PalPassiveSkillDescriptions", typeof(PalPassiveSkillDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack +10%. Fire damage reduction 15%. Lightning damage reduction 15%.
        /// </summary>
        public static string Alien {
            get {
                return ResourceManager.GetString("Alien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Skill Cooldown extension -15%.
        /// </summary>
        public static string CoolTimeReduction_Down_1 {
            get {
                return ResourceManager.GetString("CoolTimeReduction_Down_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active skill cooldown reduction 30% Attack +10%.
        /// </summary>
        public static string CoolTimeReduction_Up_1 {
            get {
                return ResourceManager.GetString("CoolTimeReduction_Up_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active skill cooldown reduction 15%.
        /// </summary>
        public static string CoolTimeReduction_Up_2 {
            get {
                return ResourceManager.GetString("CoolTimeReduction_Up_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Speed -10%.
        /// </summary>
        public static string CraftSpeed_down1 {
            get {
                return ResourceManager.GetString("CraftSpeed_down1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Speed -30%.
        /// </summary>
        public static string CraftSpeed_down2 {
            get {
                return ResourceManager.GetString("CraftSpeed_down2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Speed +20%.
        /// </summary>
        public static string CraftSpeed_up1 {
            get {
                return ResourceManager.GetString("CraftSpeed_up1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Speed +50%.
        /// </summary>
        public static string CraftSpeed_up2 {
            get {
                return ResourceManager.GetString("CraftSpeed_up2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Speed +75%.
        /// </summary>
        public static string CraftSpeed_up3 {
            get {
                return ResourceManager.GetString("CraftSpeed_up3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense -10%.
        /// </summary>
        public static string Deffence_down1 {
            get {
                return ResourceManager.GetString("Deffence_down1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense -20%.
        /// </summary>
        public static string Deffence_down2 {
            get {
                return ResourceManager.GetString("Deffence_down2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense +10%.
        /// </summary>
        public static string Deffence_up1 {
            get {
                return ResourceManager.GetString("Deffence_up1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense +20%.
        /// </summary>
        public static string Deffence_up2 {
            get {
                return ResourceManager.GetString("Deffence_up2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamond Body.
        /// </summary>
        public static string Deffence_up3 {
            get {
                return ResourceManager.GetString("Deffence_up3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10% increase to Water attack damage.
        /// </summary>
        public static string ElementBoost_Aqua_1_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Aqua_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20% increase to Water attack damage.
        /// </summary>
        public static string ElementBoost_Aqua_2_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Aqua_2_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10% increase to Dark attack damage.
        /// </summary>
        public static string ElementBoost_Dark_1_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Dark_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20% increase to Dark attack damage.
        /// </summary>
        public static string ElementBoost_Dark_2_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Dark_2_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10% increase to Dragon attack damage.
        /// </summary>
        public static string ElementBoost_Dragon_1_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Dragon_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20% increase to Dragon attack damage.
        /// </summary>
        public static string ElementBoost_Dragon_2_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Dragon_2_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10% increase to Earth attack damage.
        /// </summary>
        public static string ElementBoost_Earth_1_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Earth_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20% increase to Earth attack damage.
        /// </summary>
        public static string ElementBoost_Earth_2_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Earth_2_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10% increase to Fire attack damage.
        /// </summary>
        public static string ElementBoost_Fire_1_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Fire_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20% increase to Fire attack damage.
        /// </summary>
        public static string ElementBoost_Fire_2_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Fire_2_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10% increase to Ice attack damage.
        /// </summary>
        public static string ElementBoost_Ice_1_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Ice_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20% increase to Ice attack damage.
        /// </summary>
        public static string ElementBoost_Ice_2_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Ice_2_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10% increase to Grass attack damage.
        /// </summary>
        public static string ElementBoost_Leaf_1_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Leaf_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20% increase to Grass attack damage.
        /// </summary>
        public static string ElementBoost_Leaf_2_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Leaf_2_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10% increase to Neutral attack damage.
        /// </summary>
        public static string ElementBoost_Normal_1_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Normal_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20% increase to Normal attack damage.
        /// </summary>
        public static string ElementBoost_Normal_2_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Normal_2_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10% increase to Lightning attack damage.
        /// </summary>
        public static string ElementBoost_Thunder_1_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Thunder_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20% increase to Lightning attack damage.
        /// </summary>
        public static string ElementBoost_Thunder_2_PAL {
            get {
                return ResourceManager.GetString("ElementBoost_Thunder_2_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10% decrease to incoming Water damage.
        /// </summary>
        public static string ElementResist_Aqua_1_PAL {
            get {
                return ResourceManager.GetString("ElementResist_Aqua_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10% decrease to incoming Dark damage.
        /// </summary>
        public static string ElementResist_Dark_1_PAL {
            get {
                return ResourceManager.GetString("ElementResist_Dark_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10% decrease to incoming Dragon damage.
        /// </summary>
        public static string ElementResist_Dragon_1_PAL {
            get {
                return ResourceManager.GetString("ElementResist_Dragon_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10% decrease to incoming Ground damage.
        /// </summary>
        public static string ElementResist_Earth_1_PAL {
            get {
                return ResourceManager.GetString("ElementResist_Earth_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10% decrease to incoming Fire damage.
        /// </summary>
        public static string ElementResist_Fire_1_PAL {
            get {
                return ResourceManager.GetString("ElementResist_Fire_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10% decrease to incoming Ice damage.
        /// </summary>
        public static string ElementResist_Ice_1_PAL {
            get {
                return ResourceManager.GetString("ElementResist_Ice_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10% decrease to incoming Grass damage.
        /// </summary>
        public static string ElementResist_Leaf_1_PAL {
            get {
                return ResourceManager.GetString("ElementResist_Leaf_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10% decreased to incoming Neutral damage.
        /// </summary>
        public static string ElementResist_Normal_1_PAL {
            get {
                return ResourceManager.GetString("ElementResist_Normal_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10% decrease to incoming Lightning damage.
        /// </summary>
        public static string ElementResist_Thunder_1_PAL {
            get {
                return ResourceManager.GetString("ElementResist_Thunder_1_PAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30% increase to Fire attack damage. 30% increase Lightning attack damage.
        /// </summary>
        public static string EternalFlame {
            get {
                return ResourceManager.GetString("EternalFlame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30% increase to Dark attack damage. 30% increase to Dragon attack damage.
        /// </summary>
        public static string Invader {
            get {
                return ResourceManager.GetString("Invader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack +20%. Defense +20%. Movement Speed increases 15%.
        /// </summary>
        public static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10% increase to Movement Speed.
        /// </summary>
        public static string MoveSpeed_up_1 {
            get {
                return ResourceManager.GetString("MoveSpeed_up_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20% increase to Movement Speed.
        /// </summary>
        public static string MoveSpeed_up_2 {
            get {
                return ResourceManager.GetString("MoveSpeed_up_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30% increase to movement speed.
        /// </summary>
        public static string MoveSpeed_up_3 {
            get {
                return ResourceManager.GetString("MoveSpeed_up_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not sleep and continous to work even at night.
        /// </summary>
        public static string Nocturnal {
            get {
                return ResourceManager.GetString("Nocturnal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacifist. Will not reduce the target&apos;s Health below 1.
        /// </summary>
        public static string NonKilling {
            get {
                return ResourceManager.GetString("NonKilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack +30%. Work Speed -50%.
        /// </summary>
        public static string Noukin {
            get {
                return ResourceManager.GetString("Noukin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack -10%.
        /// </summary>
        public static string PAL_ALLAttack_down1 {
            get {
                return ResourceManager.GetString("PAL_ALLAttack_down1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack -20%.
        /// </summary>
        public static string PAL_ALLAttack_down2 {
            get {
                return ResourceManager.GetString("PAL_ALLAttack_down2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack +10%.
        /// </summary>
        public static string PAL_ALLAttack_up1 {
            get {
                return ResourceManager.GetString("PAL_ALLAttack_up1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack +20%.
        /// </summary>
        public static string PAL_ALLAttack_up2 {
            get {
                return ResourceManager.GetString("PAL_ALLAttack_up2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demon God.
        /// </summary>
        public static string PAL_ALLAttack_up3 {
            get {
                return ResourceManager.GetString("PAL_ALLAttack_up3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Speed +10%. Defense -10%.
        /// </summary>
        public static string PAL_conceited {
            get {
                return ResourceManager.GetString("PAL_conceited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Speed +30%. Attack -30%.
        /// </summary>
        public static string PAL_CorporateSlave {
            get {
                return ResourceManager.GetString("PAL_CorporateSlave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satiety drops +10% slower.
        /// </summary>
        public static string PAL_FullStomach_Down_1 {
            get {
                return ResourceManager.GetString("PAL_FullStomach_Down_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease in Hunger is less likely by +15%.
        /// </summary>
        public static string PAL_FullStomach_Down_2 {
            get {
                return ResourceManager.GetString("PAL_FullStomach_Down_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunger decreases +20% slower.
        /// </summary>
        public static string PAL_FullStomach_Down_3 {
            get {
                return ResourceManager.GetString("PAL_FullStomach_Down_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satiety drops +10% faster.
        /// </summary>
        public static string PAL_FullStomach_Up_1 {
            get {
                return ResourceManager.GetString("PAL_FullStomach_Up_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satiety drops +15% faster.
        /// </summary>
        public static string PAL_FullStomach_Up_2 {
            get {
                return ResourceManager.GetString("PAL_FullStomach_Up_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense +15%. Attack -15%.
        /// </summary>
        public static string PAL_masochist {
            get {
                return ResourceManager.GetString("PAL_masochist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack +10%. Defense -10%.
        /// </summary>
        public static string PAL_oraora {
            get {
                return ResourceManager.GetString("PAL_oraora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack +15%. Work Speed -10%.
        /// </summary>
        public static string PAL_rude {
            get {
                return ResourceManager.GetString("PAL_rude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack +15%. Defense -15%.
        /// </summary>
        public static string PAL_sadist {
            get {
                return ResourceManager.GetString("PAL_sadist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAN drops +10% slower.
        /// </summary>
        public static string PAL_Sanity_Down_1 {
            get {
                return ResourceManager.GetString("PAL_Sanity_Down_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAN drops +15% slower.
        /// </summary>
        public static string PAL_Sanity_Down_2 {
            get {
                return ResourceManager.GetString("PAL_Sanity_Down_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart of the Immovable King.
        /// </summary>
        public static string PAL_Sanity_Down_3 {
            get {
                return ResourceManager.GetString("PAL_Sanity_Down_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAN drops +10% faster.
        /// </summary>
        public static string PAL_Sanity_Up_1 {
            get {
                return ResourceManager.GetString("PAL_Sanity_Up_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAN drops +15% faster.
        /// </summary>
        public static string PAL_Sanity_Up_2 {
            get {
                return ResourceManager.GetString("PAL_Sanity_Up_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Speed +15%. Attack +15%.
        /// </summary>
        public static string Rare {
            get {
                return ResourceManager.GetString("Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale price -10%.
        /// </summary>
        public static string SalePrice_Down_1 {
            get {
                return ResourceManager.GetString("SalePrice_Down_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale price +5%.
        /// </summary>
        public static string SalePrice_Up_1 {
            get {
                return ResourceManager.GetString("SalePrice_Up_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale price +3%.
        /// </summary>
        public static string SalePrice_Up_2 {
            get {
                return ResourceManager.GetString("SalePrice_Up_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Stamina -25%.
        /// </summary>
        public static string Stamina_Down_1 {
            get {
                return ResourceManager.GetString("Stamina_Down_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Stamina +50%.
        /// </summary>
        public static string Stamina_Up_1 {
            get {
                return ResourceManager.GetString("Stamina_Up_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Stamina +25%.
        /// </summary>
        public static string Stamina_Up_2 {
            get {
                return ResourceManager.GetString("Stamina_Up_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max stamina +75%.
        /// </summary>
        public static string Stamina_Up_3 {
            get {
                return ResourceManager.GetString("Stamina_Up_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When assigned to a Breeding Farm, egg production time is reduced by 100%.
        /// </summary>
        public static string Test_PalEgg_HatchingSpeed_Up {
            get {
                return ResourceManager.GetString("Test_PalEgg_HatchingSpeed_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10% increase to Player Attack.
        /// </summary>
        public static string TrainerATK_UP_1 {
            get {
                return ResourceManager.GetString("TrainerATK_UP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10% increase to Player Defense.
        /// </summary>
        public static string TrainerDEF_UP_1 {
            get {
                return ResourceManager.GetString("TrainerDEF_UP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25% increase to Player Logging Efficiency.
        /// </summary>
        public static string TrainerLogging_up1 {
            get {
                return ResourceManager.GetString("TrainerLogging_up1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25% increase to Player Mining Efficiency.
        /// </summary>
        public static string TrainerMining_up1 {
            get {
                return ResourceManager.GetString("TrainerMining_up1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25% increase to Player Work Speed.
        /// </summary>
        public static string TrainerWorkSpeed_UP_1 {
            get {
                return ResourceManager.GetString("TrainerWorkSpeed_UP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absorbs a portion of the damage dealt to restore Health. Does not sleep at night and continues to work.
        /// </summary>
        public static string Vampire {
            get {
                return ResourceManager.GetString("Vampire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20% increase to Dark attack damage. 20% increase to Ice attack damage.
        /// </summary>
        public static string Witch {
            get {
                return ResourceManager.GetString("Witch", resourceCulture);
            }
        }
    }
}
