//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalsBreedingAdvicer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PalsBreedingAdvicer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load file.
        /// </summary>
        public static string LoadFile_btn {
            get {
                return ResourceManager.GetString("LoadFile_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To apply the changes you need to restart the application.
        /// </summary>
        public static string NeedRestart_msg {
            get {
                return ResourceManager.GetString("NeedRestart_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pal to breed.
        /// </summary>
        public static string PalToBreed_text {
            get {
                return ResourceManager.GetString("PalToBreed_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the save path.
        /// </summary>
        public static string SavePathChoosing_title {
            get {
                return ResourceManager.GetString("SavePathChoosing_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills weights.
        /// </summary>
        public static string SkillsWeights_text {
            get {
                return ResourceManager.GetString("SkillsWeights_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weights.
        /// </summary>
        public static string Weights_text {
            get {
                return ResourceManager.GetString("Weights_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy set.
        /// </summary>
        public static string WeightSetCopy_btn {
            get {
                return ResourceManager.GetString("WeightSetCopy_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create set.
        /// </summary>
        public static string WeightSetCreate_btn {
            get {
                return ResourceManager.GetString("WeightSetCreate_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete set.
        /// </summary>
        public static string WeightSetDelete_btn {
            get {
                return ResourceManager.GetString("WeightSetDelete_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string WeightSetName_text {
            get {
                return ResourceManager.GetString("WeightSetName_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string WeightSetsCancel_btn {
            get {
                return ResourceManager.GetString("WeightSetsCancel_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string WeightSetsEdit_btn {
            get {
                return ResourceManager.GetString("WeightSetsEdit_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit passive skill weight sets.
        /// </summary>
        public static string WeightSetsEditor_title {
            get {
                return ResourceManager.GetString("WeightSetsEditor_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weights sets editing window is still open. Do you want to close entire application?.
        /// </summary>
        public static string WeightSetsEditorOpened_msg {
            get {
                return ResourceManager.GetString("WeightSetsEditorOpened_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing entire application.
        /// </summary>
        public static string WeightSetsEditorOpened_title {
            get {
                return ResourceManager.GetString("WeightSetsEditorOpened_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string WeightSetsSave_btn {
            get {
                return ResourceManager.GetString("WeightSetsSave_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weights sets have changes. Do you want to exit editing without saving?.
        /// </summary>
        public static string WeightSetsUnsavedChanges_msg {
            get {
                return ResourceManager.GetString("WeightSetsUnsavedChanges_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit without saving.
        /// </summary>
        public static string WeightSetsUnsavedChanges_title {
            get {
                return ResourceManager.GetString("WeightSetsUnsavedChanges_title", resourceCulture);
            }
        }
    }
}
